# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ddd_architect}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manuel Vidaurre"]
  s.date = %q{2012-06-04}
  s.default_executable = %q{ddd_architect}
  s.description = %q{Creates a business gem skeleton with conventions for using Rails 3 engine with Rakefile, Gemfile and running tests}
  s.email = %q{manuel.vidaurre@agiltec.com.mx}
  s.executables = ["ddd_architect"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "lib/ddd_architect.rb",
    "lib/templates/gitignore",
    "lib/templates/rails/application.rb",
    "lib/templates/rails/boot.rb",
    "lib/templates/root/%underscored%.gemspec.tt",
    "lib/templates/root/Gemfile.tt",
    "lib/templates/root/MIT-LICENSE.tt",
    "lib/templates/root/README.rdoc.tt",
    "lib/templates/root/Rakefile.tt",
    "lib/templates/root/lib/%underscored%.rb.tt",
    "lib/templates/spec/%underscored%_spec.rb.tt",
    "lib/templates/spec/integration/navigation_spec.rb.tt",
    "lib/templates/spec/spec_helper.rb",
    "lib/templates/test/%underscored%_test.rb.tt",
    "lib/templates/test/integration/navigation_test.rb.tt",
    "lib/templates/test/support/integration_case.rb",
    "lib/templates/test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mvidaurre/ddd_architect}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.8.23}
  s.summary = %q{Creates a business gem skeleton with conventions for using Rails 3 engine with Rakefile, Gemfile and running tests}
  s.test_files = [
    "test/ddd_architect_test.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3.2

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, ["~> 0.15.2"])
      s.add_runtime_dependency(%q<rails>, ["~> 3.2.3"])
      s.add_runtime_dependency(%q<rake>, ["~> 0.9.2.2"])
    else
      s.add_dependency(%q<thor>, ["~> 0.15.2"])
      s.add_dependency(%q<rails>, ["~> 3.2.3"])
      s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
    end
  else
    s.add_dependency(%q<thor>, ["~> 0.15.2"])
    s.add_dependency(%q<rails>, ["~> 3.2.3"])
    s.add_dependency(%q<rake>, ["~> 0.9.2.2"])
  end
end

